title: Github Home of PerplexedStepan
description: A hub for all my projects
theme: just-the-docs

url: https://perplexedstepan.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
