title: Steve's Github Home
description: A hub for all my IT-related projects
theme: just-the-docs

url: https://perplexedstepan.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
